version: '3.8'

services:
    db:
        image: 'postgres:12'
        environment:
          - POSTGRES_DB=db
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=AVNS_9qtz1gpuZnhWhv1Ky-U
        ports:
          - '25060:25060'